/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import javax.imageio.ImageIO;
import java.sql.DriverManager;
import java.util.HashMap;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
/**
 *
 * @author xp
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Connection conexion; //almacena la conexion a la BBDD
    
    Statement estado; //almacena el estado de la conexión
    
    ResultSet resultado; //almacena el resultado de la query a la BBDD
    
    String[][] arrayResultado;
    int posi = 0;
    BufferedImage plantilla = null;
    private int ancho = 210, alto = 210;
    private int contador = 0;
    int total_pokemons = 0;
    private ResultSet resultadoConsulta;
    
    
    HashMap <String,Pokemon> listaPokemons = new HashMap();
    
    
    
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        try{
            plantilla = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
        }
        catch (IOException e){}
   
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://127.0.0.1/pokemon","root","root");
            estado = conexion.createStatement();
            resultadoConsulta = estado.executeQuery("Select * from pokemon");
            //cargo el resultado de la query en mi hashmap
            while (resultadoConsulta.next()){
                Pokemon p = new Pokemon();
                p.nombre = resultadoConsulta.getString("name");
                p.generation_id = resultadoConsulta.getInt(5);
                p.evolution_chain_id = resultadoConsulta.getInt(6);
                p.species = resultadoConsulta.getString(12);
                p.height = resultadoConsulta.getInt(10);
                p.weight = resultadoConsulta.getInt(11);
                listaPokemons.put(resultadoConsulta.getString(1), p);
            }
        }
        catch (Exception e){
        }
        total_pokemons = listaPokemons.size();
        ImagenesP.setIcon(devuelveElPokemonQueEstaEnLaPosicion(0));
        escribeDatos();
    }
     private void escribeDatos(){
        Pokemon p = listaPokemons.get(String.valueOf(contador+1));
        if (p != null){
            Nombre2.setText(p.nombre);
            Altura2.setText("" + p.height);
            Anchura2.setText("" + p.weight);
            Tipo2.setText(p.species);
            Evolucion2.setText("" + p.evolution_chain_id);
            Generacion2.setText("" + p.generation_id);
        }
        else {
            Nombre2.setText("NO HAY DATOS");
        }
    }
    
    private ImageIcon devuelveElPokemonQueEstaEnLaPosicion (int posicion){
        int columna = posicion / 30;
        int fila = posicion % 30;
        return ( new ImageIcon(plantilla.getSubimage(fila*96+1, columna*96+1, 96, 96)
                .getScaledInstance(ancho, alto, Image.SCALE_DEFAULT)));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenesP = new javax.swing.JLabel();
        Prev = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        Generacion1 = new javax.swing.JLabel();
        Generacion2 = new javax.swing.JLabel();
        Evolucion1 = new javax.swing.JLabel();
        Evolucion2 = new javax.swing.JLabel();
        Contador = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        Altura1 = new javax.swing.JLabel();
        Altura2 = new javax.swing.JLabel();
        Anchura1 = new javax.swing.JLabel();
        Anchura2 = new javax.swing.JLabel();
        Tipo1 = new javax.swing.JLabel();
        Tipo2 = new javax.swing.JLabel();
        EtiquetaI = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ImagenesP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 150));

        Prev.setBackground(new java.awt.Color(255, 255, 255));
        Prev.setForeground(new java.awt.Color(255, 255, 255));
        Prev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Prev.setText("PREV");
        Prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrevMousePressed(evt);
            }
        });
        getContentPane().add(Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 100, 30));

        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Next.setText("NEXT");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextMousePressed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 100, 30));

        Generacion1.setForeground(new java.awt.Color(255, 255, 255));
        Generacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Generacion1.setText("GENERACIÓN:");
        getContentPane().add(Generacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 80, 20));

        Generacion2.setForeground(new java.awt.Color(255, 255, 255));
        Generacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Generacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 30, 20));

        Evolucion1.setForeground(new java.awt.Color(255, 255, 255));
        Evolucion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Evolucion1.setText("EVOLUCIÓN:");
        getContentPane().add(Evolucion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 80, 20));

        Evolucion2.setForeground(new java.awt.Color(255, 255, 255));
        Evolucion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Evolucion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 30, 20));
        getContentPane().add(Contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 50));

        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre1.setText("NOMBRE:");
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 60, 20));

        Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 110, 20));

        Altura1.setForeground(new java.awt.Color(255, 255, 255));
        Altura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Altura1.setText("ALTURA:");
        getContentPane().add(Altura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 60, 20));

        Altura2.setForeground(new java.awt.Color(255, 255, 255));
        Altura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Altura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 90, 20));

        Anchura1.setForeground(new java.awt.Color(240, 240, 240));
        Anchura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anchura1.setText("ANCHURA:");
        getContentPane().add(Anchura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 80, 20));

        Anchura2.setForeground(new java.awt.Color(255, 255, 255));
        Anchura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Anchura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 110, 20));

        Tipo1.setForeground(new java.awt.Color(255, 255, 255));
        Tipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tipo1.setText("Tipo:");
        getContentPane().add(Tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 60, 20));

        Tipo2.setForeground(new java.awt.Color(240, 240, 240));
        Tipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 110, 20));

        EtiquetaI.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        EtiquetaI.setForeground(new java.awt.Color(240, 240, 240));
        EtiquetaI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaI.setText("INFO");
        getContentPane().add(EtiquetaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 50, 40));

        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokedex.png"))); // NOI18N
        getContentPane().add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevMousePressed
        contador--;
        if (contador < 0) {contador = 0;}
        //dibujaElPokemonQueEstaEnLaPosicion(contador);
        ImagenesP.setIcon(devuelveElPokemonQueEstaEnLaPosicion(contador));
         escribeDatos();
    }//GEN-LAST:event_PrevMousePressed

    private void NextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMousePressed
       contador++;
        if (contador > total_pokemons) {contador = 0;}
         ImagenesP.setIcon(devuelveElPokemonQueEstaEnLaPosicion(contador));
          escribeDatos();
    }//GEN-LAST:event_NextMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura1;
    private javax.swing.JLabel Altura2;
    private javax.swing.JLabel Anchura1;
    private javax.swing.JLabel Anchura2;
    private javax.swing.JLabel Contador;
    private javax.swing.JLabel EtiquetaI;
    private javax.swing.JLabel Evolucion1;
    private javax.swing.JLabel Evolucion2;
    private javax.swing.JLabel Generacion1;
    private javax.swing.JLabel Generacion2;
    private javax.swing.JLabel ImagenesP;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Prev;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JLabel Tipo2;
    // End of variables declaration//GEN-END:variables
}
