/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import javax.imageio.ImageIO;
import java.sql.DriverManager;
import java.util.HashMap;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import java.applet.AudioClip;
/**
 *
 * @author xp
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Connection conexion; //almacena la conexion a la BBDD
    
    Statement estado; //almacena el estado de la conexión
    
    ResultSet resultado; //almacena el resultado de la query a la BBDD
    
    String[][] arrayResultado;
    int posi = 0;
    BufferedImage plantilla = null;
    private int ancho = 210, alto = 210;
    private int contador = 0;
    int total_pokemons = 0;
    private ResultSet resultadoConsulta;
    
    
    HashMap <String,Pokemon> listaPokemons = new HashMap();
    
    
    
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/codigo/pokemon.wav"));
        sonido.play();
        try{
            plantilla = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
        }
        catch (IOException e){}
   
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://127.0.0.1/pokemon","root","root");
            estado = conexion.createStatement();
            resultadoConsulta = estado.executeQuery("Select * from pokemon");
            //cargo el resultado de la query en mi hashmap
            while (resultadoConsulta.next()){
                Pokemon p = new Pokemon();
                p.nombre = resultadoConsulta.getString("name");
                p.generation_id = resultadoConsulta.getInt(5);
                p.evolution_chain_id = resultadoConsulta.getInt(6);
                p.species = resultadoConsulta.getString(12);
                p.height = resultadoConsulta.getInt(10);
                p.weight = resultadoConsulta.getInt(11);
                p.habitat = resultadoConsulta.getString(15);
                p.color = resultadoConsulta.getString(13);
                listaPokemons.put(resultadoConsulta.getString(1), p);
            }
        }
        catch (Exception e){
        }
        total_pokemons = listaPokemons.size();
        ImagenesP.setIcon(devuelveElPokemonQueEstaEnLaPosicion(0));
        escribeDatos();
    }
     private void escribeDatos(){
        Pokemon p = listaPokemons.get(String.valueOf(contador+1));
        if (p != null){
            Nombre2.setText(p.nombre);
            Altura2.setText("" + p.height);
            Anchura2.setText("" + p.weight);
            Tipo2.setText(p.species);
            Evolucion2.setText("" + p.evolution_chain_id);
            Generacion2.setText("" + p.generation_id);
            Habitat2.setText(p.habitat);
            Color2.setText(p.color);
        }
        else {
            Nombre2.setText("NO HAY DATOS");
        }
    }
    
    private ImageIcon devuelveElPokemonQueEstaEnLaPosicion (int posicion){
        int columna = posicion / 30;
        int fila = posicion % 30;
        return ( new ImageIcon(plantilla.getSubimage(fila*96+1, columna*96+1, 96, 96)
                .getScaledInstance(ancho, alto, Image.SCALE_DEFAULT)));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenesP = new javax.swing.JLabel();
        Prev = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        Generacion1 = new javax.swing.JLabel();
        Generacion2 = new javax.swing.JLabel();
        Evolucion1 = new javax.swing.JLabel();
        Evolucion2 = new javax.swing.JLabel();
        Contador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Nombre1 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        Altura1 = new javax.swing.JLabel();
        Altura2 = new javax.swing.JLabel();
        Anchura1 = new javax.swing.JLabel();
        Anchura2 = new javax.swing.JLabel();
        Tipo1 = new javax.swing.JLabel();
        Tipo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Habitat1 = new javax.swing.JLabel();
        Habitat2 = new javax.swing.JLabel();
        Color1 = new javax.swing.JLabel();
        Color2 = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ImagenesP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 150));

        Prev.setBackground(new java.awt.Color(255, 255, 255));
        Prev.setFont(new java.awt.Font("Pokemon Hollow", 0, 24)); // NOI18N
        Prev.setForeground(new java.awt.Color(255, 255, 255));
        Prev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Prev.setText("PREV");
        Prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrevMousePressed(evt);
            }
        });
        getContentPane().add(Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 100, 30));

        Next.setFont(new java.awt.Font("Pokemon Hollow", 0, 24)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Next.setText("NEXT");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextMousePressed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 100, 30));

        Generacion1.setFont(new java.awt.Font("Pokemon Hollow", 1, 12)); // NOI18N
        Generacion1.setForeground(new java.awt.Color(255, 255, 255));
        Generacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Generacion1.setText("GENERACIÓN:");
        getContentPane().add(Generacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 90, 20));

        Generacion2.setForeground(new java.awt.Color(255, 255, 255));
        Generacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Generacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 20, 20));

        Evolucion1.setFont(new java.awt.Font("Pokemon Hollow", 1, 11)); // NOI18N
        Evolucion1.setForeground(new java.awt.Color(255, 255, 255));
        Evolucion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Evolucion1.setText("EVOLUCIÓN:");
        getContentPane().add(Evolucion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 80, 20));

        Evolucion2.setForeground(new java.awt.Color(255, 255, 255));
        Evolucion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Evolucion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 30, 20));
        getContentPane().add(Contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 50));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 60, 10));

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre1.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        Nombre1.setText("Nombre:");
        jPanel1.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        Nombre2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jPanel1.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 14, 160, 20));

        Altura1.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        Altura1.setText("Altura:");
        jPanel1.add(Altura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        Altura2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jPanel1.add(Altura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 100, 20));

        Anchura1.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        Anchura1.setText("Anchura:");
        jPanel1.add(Anchura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        Anchura2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jPanel1.add(Anchura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 84, 90, 20));

        Tipo1.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        Tipo1.setText("Tipo:");
        jPanel1.add(Tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        Tipo2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jPanel1.add(Tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, 20));

        jLabel2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 74, 50, 30));

        Habitat1.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        Habitat1.setText("Habitat:");
        jPanel1.add(Habitat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        Habitat2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jPanel1.add(Habitat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, 20));

        Color1.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        Color1.setText("Color:");
        jPanel1.add(Color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        Color2.setFont(new java.awt.Font("Pokemon Hollow", 0, 18)); // NOI18N
        jPanel1.add(Color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 260, 210));

        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokedex.png"))); // NOI18N
        getContentPane().add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevMousePressed
        contador--;
        if (contador < 0) {contador = 0;}
        //dibujaElPokemonQueEstaEnLaPosicion(contador);
        ImagenesP.setIcon(devuelveElPokemonQueEstaEnLaPosicion(contador));
         escribeDatos();
    }//GEN-LAST:event_PrevMousePressed

    private void NextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMousePressed
       contador++;
        if (contador > total_pokemons) {contador = 0;}
         ImagenesP.setIcon(devuelveElPokemonQueEstaEnLaPosicion(contador));
          escribeDatos();
    }//GEN-LAST:event_NextMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura1;
    private javax.swing.JLabel Altura2;
    private javax.swing.JLabel Anchura1;
    private javax.swing.JLabel Anchura2;
    private javax.swing.JLabel Color1;
    private javax.swing.JLabel Color2;
    private javax.swing.JLabel Contador;
    private javax.swing.JLabel Evolucion1;
    private javax.swing.JLabel Evolucion2;
    private javax.swing.JLabel Generacion1;
    private javax.swing.JLabel Generacion2;
    private javax.swing.JLabel Habitat1;
    private javax.swing.JLabel Habitat2;
    private javax.swing.JLabel ImagenesP;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Prev;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JLabel Tipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
